


metta_knowledge = '''
            !(add-atom &self (CV ((description "Update your CV every week for HR review") (frequency 'Weekly') (importance 'High'))))
!(add-atom &self (Meeting ((Monday ((description 'Staff meeting to present weekly progress and plan') (frequency "Weekly") (mandatory "for both staff and interns") (time "7:00 AM - 8:00 AM")))
                    (Wednesday ((description 'Intern meeting to present weekly progress and plan') (frequency 'Weekly') (mandatory 'only for interns') (time "7:00 AM - 8:00 AM"))))))
!(add-atom &self (Responsibility ((Attendance "Minimum 40 office hours per month") 
                                (CV "Update CV every week before Sunday midnight") 
                                (Training "Attend training every Saturday") 
                                (Confidentiality "Maintain confidentiality of company information and proprietary data") 
                                (Professionalism "Maintain professional demeanor and respect in all interactions")
                                (Task-Completion "Complete assigned tasks on time and report progress to supervisors")
                                (Documentation "Maintain proper documentation for work and progress updates"))))
!(add-atom &self (Mentor ((description "Each intern at iCog-Labs has a mentor for guidance") 
                        (change "To change a mentor, interns must inform HR") 
                        (responsibility "Mentors guide interns in their projects") 
                        (work "Interns and mentors collaborate on mentor-led projects")
                        (feedback "Mentors provide regular feedback to interns on performance and skill development"))))
!(add-atom &self (Mentor-Change ((description "To change a mentor, inform HR") 
                                (process "HR will assign a new mentor upon request"))))
!(add-atom &self (Training ((description "Training sessions are mandatory and occur on Saturdays") 
                            (grading "Intern performance is evaluated based on attendance and engagement") 
                            (courses "Interns must complete five mandatory courses during their internship")
                            (participation "Active participation in training is required to qualify for further internship opportunities"))))
!(add-atom &self (Performance-Evaluation ((description "Interns are evaluated based on performance and attendance") 
                                        (grouping "Top 5 in Group 1 are prioritized for intern-to-staff transition")
                                        (criteria "Evaluation includes punctuality, work quality, communication, and team collaboration"))))
!(add-atom &self (Communication ((description "Interns must maintain open communication with mentors and team members") 
                                (reporting "Interns should regularly update project progress and challenges") 
                                (official-channels "Use official channels for communication and documentation submission")
                                (email "Use professional email etiquette when communicating with HR and supervisors"))))
!(add-atom &self (Key-Contacts ((HR "icoglabs89@gmail.com, icoghrteam1@gmail.com") 
                                (Mentor "Assigned mentor for guidance") 
                                (Team-Leads "Project-specific questions directed to respective team leads"))))
!(add-atom &self (Work-Ethics ((Punctuality "Interns must arrive on time for meetings and work sessions") 
                            (Respect "Respect colleagues, mentors, and staff members") 
                            (Teamwork "Collaborate effectively with peers and contribute to group tasks")
                            (Integrity "Uphold honesty and transparency in all tasks and reporting"))))
!(add-atom &self (Leave-Policy ((Request "Interns must request leave in advance and get approval from HR") 
                                (Limitations "Unapproved absences may affect performance evaluation")
                                (Emergency "In case of emergencies, notify HR and mentors immediately"))))
!(add-atom &self (Internship-Completion ((Certificate "Interns receive a certificate upon successful completion") 
                                        (Extension "Outstanding interns may be offered an extended internship or job opportunity")
                                        (Final-Review "HR and mentors conduct a final review before internship completion"))))
!(add-atom &self (Hello ((description "Hello, I am an AI designed to assist with HR-related queries")
                        (functionality "I can provide information on company policies, responsibilities, and HR procedures")
                        (knowledge "I have access to the latest HR data and guidelines")
                        (limitations "I cannot provide legal advice or personal opinions"))))
!(add-atom &self (Goodbye ((description "Goodbye, I hope I was able to assist you with your HR query")
                        (functionality "I can provide information on company policies, responsibilities, and HR procedures")
                        (knowledge "I have access to the latest HR data and guidelines")
                        (limitations "I cannot provide legal advice or personal opinions"))))
!(add-atom &self (help ((description "I can provide information on company policies, responsibilities, and HR procedures")
                        (functionality "I have access to the latest HR data and guidelines")
                        (limitations "I cannot provide legal advice or personal opinions"))))
!(add-atom &self (HR-Query ((description "I can provide information on company policies, responsibilities, and HR procedures")
                        (functionality "I have access to the latest HR data and guidelines")
                        (limitations "I cannot provide legal advice or personal opinions"))))
!(add-atom &self (HR-Response ((description "I can provide information on company policies, responsibilities, and HR procedures")
                        (functionality "I have access to the latest HR data and guidelines")
                        (limitations "I cannot provide legal advice or personal opinions"))))
!(add-atom &self (start ((description "Hello, I am an AI designed to assist with HR-related queries at Icog-Lab AI research center")
                        (functionality "I can provide information on company policies, responsibilities, and HR procedures")
                        (knowledge "I have access to the latest HR data and guidelines")
                        (limitations "I cannot provide legal advice or personal opinions"))))
!(add-atom &self (contact ("HR contact email icoglabs89@gmail.com, icoghrteam1@gmail.com" )))
!(add-atom &self (Apply-Internship ((description "To apply for an internship, submit your CV and cover letter to HR")
                        (eligibility "Internships are open to students and recent graduates")
                        (selection "Candidates are selected based on qualifications and interview performance")
                        (duration "Internships typically last 3-6 months"))))
!(add-atom &self (Working-Hours (description "Interns are expected to work a minimum of 40 hours per month")))
!(add-atom &self (Office-Hours ((description "Office hours are from 8:00 AM to 8:00 PM, Monday to Saturday and also Sunday the office is open but may be in it will be closed so contact before coming"))))
!(add-atom &self (Icong-Lab-Location (description ("Icog-Labs is located at Bole wello sefer at Atlas Building, Addis Ababa, Ethiopia"))))
!(add-atom &self (Internship-Opportunity ((description "Interns may be offered job opportunities based on performance and availability")
                        (criteria "Top interns are considered for job openings at Icog-Labs")
                        (transition "Successful interns may transition to full-time staff positions"))))
!(add-atom &self (Internship-Feedback ((description "Interns receive feedback on performance and progress regularly")
                        (improvement "Feedback is provided to help interns improve their skills and performance")
                        (evaluation "Performance evaluations are conducted to assess intern progress and development"))))
!(add-atom &self (Internship-Training ((description "Training sessions are conducted to enhance intern skills and knowledge")
                        (topics "Training covers various topics relevant to AI research and development")
                        (participation "Active participation in training is required for intern development"))))
!(add-atom &self (Evaluation ((Posetive evaluation for every training task you will be evaluated based on your performance for the task
                            also for every complition of course you will be evaluated) (negative evaluation if you miss meeting or training you will
                            get negative evaluation also if you don't submit your task on time you will get negative evaluation consider as
                            you didn't present on the training) (based on this evaluation you will be assigned to specific group for training)
                            )))
!(add-atom &self (Evaluation-Grouping ((Group1 are prioritized for intern-to-staff transition)
                                        (to join ICOG-Lab staff you must be in group1))))
!(add-atom &self (Greeting (description give your Greeting to the user and ask how you can help)))
!(add-atom &self (CV have-relation Responsibility))
!(add-atom &self (Training have-relation Responsibility))
!(add-atom &self (Evaluation have-relation Evaluation-Grouping))
            '''
